//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.BusinessProcess
{
    using OnlineBanking.DataModel;
    using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    /// <summary>
    /// The abstract transaction manager.
    /// </summary>
	public class TransactionManagerBase
	{
        /// <summary>
        /// Shared function for logging transactions.
        /// </summary>
		protected virtual TransactionLog transactionLog
		{
			get;
			set;
		}

	}
}

