//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnlineBanking.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Text;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The log that transactions are written to. 
    /// The design shows this class as an entity class that is equivilent to the Transaction, 
    /// The implimentation works with transaction objects instead.
    /// </summary>
	public class TransactionLog
	{
        /// <summary>
        /// Log the transaction.
        /// </summary>
        /// <param name="Transaction"></param>
		public virtual void Log(Transaction Transaction)
		{
			throw new System.NotImplementedException();
		}

        /// <summary>
        /// Read the set of transactions between the given times.
        /// </summary>
        /// <param name="fromTime">The begining time to read transactions.</param>
        /// <param name="toTime">The ending time to read transactions.</param>
        /// <returns>The list of transactions between the given times.</returns>
		public virtual IEnumerable<Transaction> ReadTransaction(DateTime fromTime, DateTime toTime)
		{
			throw new System.NotImplementedException();
		}

	}
}

